[project]
name = "penguins-classifier"
version = "0.1.0"
requires-python = ">=3.8"

dependencies = [
    "fastapi",
    "uvicorn",
    "pandas",
    "seaborn",
    "xgboost",
    "scikit-learn",
    "pydantic",
    "locust>=2.25.0",
]
